import { chromium } from 'playwright';
const base = 'https://154-41-135-175.sslip.io';
const dir = 'C:/Users/kfcku/AppData/Local/Temp/claude/c--Users-kfcku-Desktop-Minsk/714ac2e3-bda0-4551-99dc-8243bc5d0bd1/scratchpad';
const b = await chromium.launch();
const page = await b.newPage({ viewport: { width: 1440, height: 900 } });
const s = Date.now();
await page.goto(`${base}/auth`, { waitUntil: 'networkidle' });
await page.getByRole('button', { name: /sign up|create/i }).first().click();
await page.waitForSelector('input[name="name"]');
await page.fill('input[name="name"]', 'Look Test');
await page.fill('input[name="email"]', `look${s}@example.com`);
await page.fill('input[name="password"]', 'password123');
await page.click('button[type="submit"]');
await page.waitForLoadState('networkidle');
await page.waitForTimeout(900);
await page.locator('aside button[aria-haspopup="menu"]').click();
await page.waitForTimeout(400);
await page.getByRole('menuitem', { name: /upgrade/i }).click();
await page.waitForTimeout(900);
await page.screenshot({ path: `${dir}/v-monthly.png` });
console.log('месяц:', await page.evaluate(() => [...document.querySelectorAll('[role="dialog"] p span')].map(e=>e.textContent).filter(t=>t.startsWith('$'))));
await page.getByRole('button', { name: /^Yearly/ }).click();
await page.waitForTimeout(500);
console.log('год:  ', await page.evaluate(() => [...document.querySelectorAll('[role="dialog"] p span')].map(e=>e.textContent).filter(t=>t.startsWith('$'))));
console.log('подпись:', (await page.evaluate(() => [...document.querySelectorAll('[role="dialog"] p')].map(e=>e.textContent).filter(t=>t.includes('billed')))).filter(Boolean));
await page.screenshot({ path: `${dir}/v-yearly.png` });
// Высота карточек не должна прыгать при переключении
const h = await page.evaluate(() => [...document.querySelectorAll('[role="dialog"] ul')].map(e => Math.round(e.getBoundingClientRect().height)));
console.log('высоты карточек:', h, new Set(h).size === 1 ? '(одинаковые)' : '(РАЗНЫЕ)');
await b.close();
